apiVersion: v1
kind: Service
metadata:
  name: argocd-server-lb
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd.opnsense.local
spec:
  # type: ClusterIP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
  - name:  https
    port:  443
    targetPort: 8080
    protocol: TCP