apiVersion: v1
kind: Namespace
metadata:
  name: httpd-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: httpd-ns
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-app
        image: httpd
        ports:
        - name: http
          containerPort: 80