apiVersion: v1
kind: Service
metadata:
  name: httpd-svc-anno
  namespace: httpd-ns

  # annotations:
  #   kubectl.kubernetes.io/last-applied-configuration: | 
  #     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"httpd-svc","namespace":"httpd-ns"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"httpd"},"type":"ThinhPhung"}}
spec:
  # type: ClusterIP
  type: LoadBalancer
  selector:
    app: httpd
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  # loadBalancerIP: 172.18.18.90