apiVersion: v1
kind: Service
metadata:
  name: httpd-svc-cluster
  namespace: httpd-ns
spec:
  selector:
    app: httpd
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80